#!/usr/bin/env bash

set -eu

outdir="processed_data/vvul/rnaseq/index"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi
log_file="${outdir}/index_log.txt"

FASTA="processed_data/vvul/scaffolds_renamed.fasta" 
GFF="processed_data/vvul/maker_filtered.gff3"
gtf="${outdir}/maker_filtered.gtf"

# convert the GFF to GTF (works better for quantification)
gffread -T "${GFF}" -o "${gtf}"

# generate STAR index
cmd=( bin/STAR 
          --runThreadN 20
          --runMode genomeGenerate
          --genomeDir "${outdir}"
          --genomeFastaFiles "${FASTA}"
          --sjdbGTFfile "${gtf}"
          --sjdbGTFtagExonParentTranscript transcript_id
          --sjdbGTFtagExonParentGene gene_id
          --sjdbOverhang 99 )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" &> "${log_file}" &
wait

metadata_file="${outdir}/METADATA.csv"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    STAR version,$(bin/STAR --version)
_EOF_
