#!/usr/bin/env bash

outdir="processed_data/vvul/rnaseq/pass1"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

read_folder="raw_data/vvul/rnaseq/NZGL01162"
index="processed_data/vvul/rnaseq/index"

# loop over sample_ids in csv file
while IFS="," read -r sample r1 r2
do
    r1_file="${read_folder}/${r1}"
    r2_file="${read_folder}/${r2}"
    printf "sample:\t%s\nr1:\t%s\nr2:\t%s\n" \
        "${sample}" "${r1_file}" "${r2_file}"

    # set up log files
    log_file="${outdir}/${sample}_log.txt"
    metadata_file="${outdir}/${sample}_METADATA.csv"

    # set up STAR job
    cmd=( bin/STAR
              --runThreadN 20
              --genomeDir "${index}"
              --readFilesIn "${r1_file}" "${r2_file}" 
              --readFilesCommand zcat
              --outFileNamePrefix "${outdir}/${sample}."
              --outSAMtype None )
    printf "Final command line: "
    printf "%s " "${cmd[@]//+([[:blank:]])/ }"
    printf "\n"
    shopt -u extglob

    # run STAR
    "${cmd[@]}" &> "${log_file}"

    # log metadata
    cat <<- _EOF_ > "${metadata_file}"
        Script,${0}
        date,$(date +%F)
        STAR version,$(bin/STAR --version)
_EOF_

done < raw_data/vvul/rnaseq/rnaseq_sample_ids.csv

wait

exit 0
