#!/usr/bin/env bash

set -eu

FASTA="processed_data/vvul/scaffolds_renamed.fasta"
OUTDIR="processed_data/vvul/tblastn/"

db="${OUTDIR}/db/scaffolds_renamed"

AMEL_QUERY="raw_data/vvul/tblastn/amel_OGSv3.2_pep.fa"
AMEL_HITS="${OUTDIR}/amel_OGSv3.2_pep_hits.blast"
AMEL_GFF="${OUTDIR}/amel_OGSv3.2_pep_hits.gff3"

PDOM_QUERY="raw_data/vvul/tblastn/GCF_001465965.1_Pdom_r1.2_protein.faa"
PDOM_HITS="${OUTDIR}/Pdom_r1.2_protein_hits.blast"
PDOM_GFF="${OUTDIR}/Pdom_r1.2_protein_hits.gff3"

num_cpus=20

# make blast db
dbdir=$(dirname "${db}")
if [[ ! -e "${dbdir}" ]]; then
    mkdir -p "${dbdir}"
fi
makeblastdb -dbtype nucl -in "${FASTA}" \
    -out "${db}"

# run blast queries
tblastn -query "${AMEL_QUERY}" \
    -db "${db}" \
    -evalue 1e-6 \
    -out "${AMEL_HITS}" \
    -num_threads "${num_cpus}" &

tblastn -query "${PDOM_QUERY}" \
    -db "${db}" \
    -evalue 1e-6 \
    -out "${PDOM_HITS}" \
    -num_threads "${num_cpus}" &

wait

# convert results to gff
bp_search2gff.pl -i "${AMEL_HITS}" \
    -o "${AMEL_GFF}" \
    -f blast \
    --type hit \
    --source tblastn \
    --target \
    --version 3 \
    --match \
    --addid \
    --cutoff 1e-6 &

bp_search2gff.pl -i "${PDOM_HITS}" \
    -o "${PDOM_GFF}" \
    -f blast \
    --type hit \
    --source tblastn \
    --target \
    --version 3 \
    --match \
    --addid \
    --cutoff 1e-6 &

wait
