#!/usr/bin/env bash

set -eu

PERL="/usr/bin/perl"
PERL5LIB="${PERL5LIB}:$(readlink -f bin/jbrowse_libs)"

FASTA="raw_data/vvulgr3/Vvulg.assembly.fna" 
GFF="raw_data/vvulgr3/Vvulg.r3.annotated.gff3"

outdir="apollo_data/vvul"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi

blatdir="${outdir}/blat"
if [[ ! -e "${blatdir}" ]]; then
  mkdir -p "${blatdir}"
fi

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/apollo/prepare-refseqs.pl \
    --fasta "${FASTA}" \
    --out "${outdir}"

# load MAKER gff
printf "[ %s: Running flatfile-to-json.pl on maker annotation ]\n" "$(date)"
"${PERL}" bin/apollo/flatfile-to-json.pl \
    --gff "${GFF}" \
    --type "mRNA" \
    --trackLabel "vvulgr3" \
    --key "Vespula vulgaris r3" \
    --out "${outdir}" 


