#!/usr/bin/env bash

set -eu

samtools=bin/samtools/samtools

FASTA="processed_data/aswmtdna/aswmtDNA.fasta"
bamfile="raw_data/aswmtdna/lr_mapped.bam"
sorted_bam="processed_data/aswmtdna/lr_mapped.bam"

# subsample the alignments
printf "[ %s: Subsampling alignments ]\n" "$(date)"
"${samtools}" view \
    -h -s 0.1 \
    "${bamfile}" \
    | "${samtools}" sort \
        -@ 50 \
        -m 5G \
        -l 9 \
        -o "${sorted_bam}" \
        --reference "${FASTA}"

printf "[ %s: Indexing BAMfile ]\n" "$(date)"
"${samtools}" index "${sorted_bam}"

exit 0
