#!/usr/bin/env bash

PERL="/usr/bin/perl"

FASTA="processed_data/vvulmtdna/Vvul-mtDNA.fasta"
GFF="processed_data/vvulmtdna/vvul_mitos_fixed.gff"

outdir="apollo_data/vvulmtdna"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi
blatdir="${outdir}/blat"
if [[ ! -e "${blatdir}" ]]; then
  mkdir -p "${blatdir}"
fi

# make a blat index
printf "[ %s: Running faToTwoBit ]\n" "$(date)"
/usr/local/bin/faToTwoBit "${FASTA}" "${blatdir}/vvmtdna.2bit"

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/apollo/prepare-refseqs.pl \
    --fasta "${FASTA}" \
    --out "${outdir}"

# prepare "gff" (mitos gff looks strange)
printf "[ %s: Running flatfile-to-json.pl on maker annotation ]\n" "$(date)"
"${PERL}" bin/apollo/flatfile-to-json.pl \
    --gff "${GFF}" \
    --trackLabel "mitos" \
    --key "MITOS annotation" \
    --type "exon,rRNA,tRNA" \
    --out "${outdir}"

# add bam file
if [[ ! -e "${outdir}/rnaseq" ]]; then
    mkdir -p "${outdir}/rnaseq"
fi
ln -s "processed_data/vvul/rnaseq/merged/*" "${outdir}/rnaseq/"

"${PERL}" bin/apollo/add-bam-track.pl \
    --bam_url "rnaseq/sorted.bam" \
    --label "rnaseq" --key "RNAseq reads" \
    --in "${outdir}/trackList.json"

# generate index
printf "[ %s: Running generate-names.pl ]\n" "$(date)"
"${PERL}" bin/apollo/generate-names.pl \
    --verbose \
    --out "${outdir}"

chmod -R a=rwx "${outdir}"

