#!/usr/bin/env bash

PERL="/usr/bin/perl"

FASTA="dataraw/dmel_test/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna" 
GFF="dataraw/dmel_test/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.gff"

outdir="data/dmel"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/apollo/prepare-refseqs.pl \
    --fasta "${FASTA}" \
    --out "${outdir}"

# load MAKER gff
printf "[ %s: Running flatfile-to-json.pl on maker annotation ]\n" "$(date)"
"${PERL}" bin/apollo/flatfile-to-json.pl \
    --gff "${GFF}" \
    --type "gene" \
    --trackLabel "maker" \
    --trackType "CanvasFeatures" \
    --key "MAKER genome annotation" \
    --out "${outdir}"

# generate index
printf "[ %s: Running generate-names.pl ]\n" "$(date)"
"${PERL}" bin/apollo/generate-names.pl \
    --verbose \
    --out "${outdir}"

# make world readable
chmod -R a=rwx "${outdir}"
exit 0
