#!/usr/bin/env bash
set -eu

FASTA="dataraw/vvmtdna/Vvul-mtDNA.fasta"

# make temporary output folder
read_folder="dataraw/NZGL01162"
outdir="rnaseq/vvmtdna"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi
tmp_dir="$(mktemp -d --tmpdir "repair.XXXXXX")"
printf "[ %s: Using tmpdir %s ]\n" "$(date)" "${tmp_dir}"

# make bwamem index
bwa index "${FASTA}" &

# loop over sample_ids in csv file and interleave
while IFS="," read -r sample r1 r2
do
    r1_file="${read_folder}/${r1}"
    r2_file="${read_folder}/${r2}"
    repaired_reads="${tmp_dir}/${sample}.fastq.gz"

    cmd=( bin/bbmap/repair.sh
              in="${r1_file}"
              in2="${r2_file}"
              out="${repaired_reads}"
              repair )

    "${cmd[@]}" &
done < dataraw/rnaseq_sample_ids.csv
wait

# find interleaved read files
repaired_files=()
while IFS="" read -r -d $'\0'; do
    repaired_files+=("$REPLY")
done < <(find "${tmp_dir}/" \
         -name "*.fastq.gz" -print0)

# join reads
merged_reads="${tmp_dir}/merged.fastq.gz"
cat "${repaired_files[@]}" > "${merged_reads}"

# map reads
aligned_sam="${tmp_dir}/aln.sam"
aligned_bam="${outdir}/aln.bam"
bwa mem -t 15 -p \
    "${FASTA}" \
    "${merged_reads}" \
    > "${aligned_sam}"

# sort the samfile to BAM
samtools sort \
    -I 9 \
    -o "${aligned_bam}" \
    -@ 15

samtools index "${aligned_bam}"

exit 0
