#!/usr/bin/env bash

PERL="/usr/bin/perl"

FASTA="dataraw/scaffolds_sorted.fasta"
GFF="dataraw/waspass.all.vvul.gff"

outdir="data/sorted"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/prepare-refseqs.pl \
    --fasta "${FASTA}" \
    --out "${outdir}"

# load MAKER gff
printf "[ %s: Running flatfile-to-json.pl ]\n" "$(date)"
"${PERL}" bin/flatfile-to-json.pl \
    --gff "${GFF}" \
    --arrowheadClass trellis-arrowhead \
    --subfeatureClasses '{"CDS":"green",
                          "contig":"grey",
                          "exon":"lightblue",
                          "gene":"blue",
                          "match":"grey",
                          "match_part":"grey",
                          "mRNA":"lightblue",
                          "five_prime_UTR":"darkgreen",
                          "three_prime_UTR":"darkgreen"}' \
    --type mRNA \
    --trackLabel maker \
    --out "${outdir}"

# generate index
printf "[ %s: Running generate-names.pl ]\n" "$(date)"
"${PERL}" bin/generate-names.pl \
    --verbose \
    --out "${outdir}"

# make a blat database... doesn't seem to do anything
/usr/local/bin/faToTwoBit "${FASTA}" "${outdir}/vv.2bit"

# make the whole outdir rwx-able, so that tomcat can read it
chmod -R a=rwx "${outdir}"

exit 0
