#!/usr/bin/env bash

PERL="/usr/bin/perl"

FASTA="dataraw/vvmtdna/Vvul_longest_quick_scaffold-it12_noIUPAC.fasta" 
FASTA_RENAMED="dataraw/vvmtdna/Vvul-mtDNA.fasta"
GFF="dataraw/vvmtdna/vvul_mitos_fixed.gff"

outdir="data/vvmtdna"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi

# fix fasta file name
sed "s/^>.*/>Vvul-mtDNA/" "${FASTA}" > "${FASTA_RENAMED}"

# fix mitobim gff
printf "[ %s: Fixing gff ]\n" "$(date)"
scripts/fix_mitos_gff.R

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/apollo/prepare-refseqs.pl \
    --fasta "${FASTA_RENAMED}" \
    --out "${outdir}"

# prepare "gff" (mitos gff looks strange)
printf "[ %s: Running flatfile-to-json.pl on maker annotation ]\n" "$(date)"
"${PERL}" bin/apollo/flatfile-to-json.pl \
    --gff "${GFF}" \
    --trackLabel "mitos" \
    --key "MITOS annotation" \
    --trackType "CanvasFeatures" \
    --type "mRNA,rRNA,tRNA" \
    --out "${outdir}"

# generate index
printf "[ %s: Running generate-names.pl ]\n" "$(date)"
"${PERL}" bin/apollo/generate-names.pl \
    --verbose \
    --out "${outdir}"

chmod -R a=rwx "${outdir}"

