#!/usr/bin/env bash

FASTA="dataraw/scaffolds_sorted.fasta"
QUERY="dataraw/amel_OGSv3.2_pep.fa"
DB="tblastn_test/scaffolds_sorted"
HITS="amel_protein_blast/amel_OGSv3.2_pep_hits.xml"

num_cpus=20

# make blast db
makeblastdb -dbtype nucl -in "${FASTA}" \
    -out "${DB}"

# run blast query
tblastn -query "${QUERY}" \
    -db "${DB}" \
    -evalue 1e-6 \
    -out "${HITS}" \
    -outfmt 5 \
    -num_threads = "${num_cpus}" \
