#!/usr/bin/env bash

PERL="/usr/bin/perl"

FASTA="dataraw/wpip_test/GCF_000742435.1_ASM74243v1_genomic.fna" 
GFF="dataraw/wpip_test/GCF_000742435.1_ASM74243v1_genomic.gff"

outdir="data/wpip"
if [[ ! -e "${outdir}" ]]; then
  mkdir -p "${outdir}"
fi

# prepare refseqs
printf "[ %s: Running prepare-refseqs.pl ]\n" "$(date)"
"${PERL}" bin/apollo/prepare-refseqs.pl \
    --fasta "${FASTA}" \
    --out "${outdir}"

# load MAKER gff
printf "[ %s: Running flatfile-to-json.pl on maker annotation ]\n" "$(date)"
"${PERL}" bin/apollo/flatfile-to-json.pl \
    --gff "${GFF}" \
    --type "CDS" \
    --trackLabel "maker" \
    --key "maker" \
    --out "${outdir}"

# generate index
printf "[ %s: Running generate-names.pl ]\n" "$(date)"
"${PERL}" bin/apollo/generate-names.pl \
    --verbose \
    --out "${outdir}"

# make world readable
chmod -R a=rwx "${outdir}"
exit 0
